import type { ModelSource } from './types';

export const TOWN_MODEL_SOURCES: ModelSource[] = [
  {
    id: 'natural-england-nca',
    organisation: 'Natural England / Defra',
    title: 'National Character Area profiles',
    url: 'https://www.gov.uk/guidance/national-character-area-profiles-information-for-local-decision-making',
    usedFor: 'regional landscape, geodiversity, biodiversity, land-use and historical-character priors',
  },
  {
    id: 'bgs-regional',
    organisation: 'British Geological Survey',
    title: 'Regional geological summaries',
    url: 'https://www.bgs.ac.uk/geology-projects/regional-geological-summaries/',
    usedFor: 'regional lithology mixtures and the coupling of rock, relief, permeability and mineral legacy',
  },
  {
    id: 'ea-catchments',
    organisation: 'Environment Agency',
    title: 'Catchment Data Explorer: catchment hierarchy and water bodies',
    url: 'https://environment.data.gov.uk/catchment-planning/help/usage',
    usedFor: 'catchment hierarchy, river-waterbody framing and downstream environmental constraints',
  },
  {
    id: 'ons-bua',
    organisation: 'Office for National Statistics',
    title: 'Towns and cities: characteristics of built-up areas, Census 2021',
    url: 'https://www.ons.gov.uk/peoplepopulationandcommunity/housing/articles/townsandcitiescharacteristicsofbuiltupareasenglandandwales/census2021',
    usedFor: 'settlement size classes and demographic scaling with built-up-area size',
  },
  {
    id: 'ons-geography',
    organisation: 'Office for National Statistics',
    title: 'Census 2021 geographies',
    url: 'https://www.ons.gov.uk/methodology/geography/ukgeographies/censusgeographies/census2021geographies',
    usedFor: 'small-area population ranges and distinction between wards, OAs, LSOAs and MSOAs',
  },
  {
    id: 'ons-ethnicity',
    organisation: 'Office for National Statistics',
    title: 'Ethnic group, England and Wales: Census 2021',
    url: 'https://www.ons.gov.uk/peoplepopulationandcommunity/culturalidentity/ethnicity/bulletins/ethnicgroupenglandandwales/census2021',
    usedFor: 'high-level self-identified ethnic-group categories and broad regional priors',
  },
  {
    id: 'imd-2019',
    organisation: 'Ministry of Housing, Communities and Local Government',
    title: 'English indices of deprivation 2019: technical report',
    url: 'https://www.gov.uk/government/publications/english-indices-of-deprivation-2019-technical-report',
    usedFor: 'multidimensional relative-deprivation framing; the generator does not claim to reproduce IMD scores',
  },
  {
    id: 'dft-nts-2024',
    organisation: 'Department for Transport',
    title: 'National Travel Survey 2024',
    url: 'https://www.gov.uk/government/statistics/national-travel-survey-2024',
    usedFor: 'national trip-purpose, mode and distance reference envelopes used to anchor scenario assumptions',
  },
  {
    id: 'dft-tag-m21',
    organisation: 'Department for Transport',
    title: 'TAG Unit M2.1: Variable Demand Modelling',
    url: 'https://www.gov.uk/government/publications/diadem-software/',
    usedFor: 'transport-demand structure and explicit separation of frequency, destination and mode choices',
  },
  {
    id: 'defra-air',
    organisation: 'Defra UK-AIR',
    title: 'Modelled background pollution data',
    url: 'https://uk-air.defra.gov.uk/data/pcm-data',
    usedFor: '1 km background-model precedent, pollutant units and uncertainty framing',
  },
  {
    id: 'defra-noise',
    organisation: 'Defra',
    title: 'Strategic noise mapping (2022)',
    url: 'https://www.gov.uk/government/publications/strategic-noise-mapping-2022',
    usedFor: 'road/rail noise indicators and map interpretation; values here remain simplified proxies',
  },
  {
    id: 'natural-england-biodiversity',
    organisation: 'Natural England',
    title: 'Statutory biodiversity metric tools and guides',
    url: 'https://www.gov.uk/government/publications/statutory-biodiversity-metric-tools-and-guides',
    usedFor: 'habitat distinctiveness/condition framing; the displayed index is not a statutory biodiversity unit calculation',
  },
  {
    id: 'place-names',
    organisation: 'University of Nottingham Institute for Name-Studies',
    title: 'Key to English Place-Names',
    url: 'https://www.nottingham.ac.uk/ins/key-to-english-place-names.aspx',
    usedFor: 'regional linguistic strata and place-name element meanings',
  },
  {
    id: 'historic-england-suburbs',
    organisation: 'Historic England',
    title: 'Understanding Suburban Heritage',
    url: 'https://historicengland.org.uk/research/current/discover-and-understand/urban-public-realm/suburbs/',
    usedFor: 'historical suburban forms and development-period distinctions',
  },
  {
    id: 'ons-education',
    organisation: 'Office for National Statistics',
    title: 'Education, England and Wales: Census 2021',
    url: 'https://www.ons.gov.uk/peoplepopulationandcommunity/educationandchildcare/bulletins/educationenglandandwales/census2021',
    usedFor: 'qualification categories and broad regional reference shares',
  },
  {
    id: 'ons-housing',
    organisation: 'Office for National Statistics',
    title: 'Housing, England and Wales: Census 2021',
    url: 'https://www.ons.gov.uk/peoplepopulationandcommunity/housing/bulletins/housingenglandandwales/census2021',
    usedFor: 'tenure and accommodation reference distributions',
  },
  {
    id: 'ons-occupation',
    organisation: 'Office for National Statistics',
    title: 'Industry and occupation, England and Wales: Census 2021',
    url: 'https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/bulletins/industryandoccupationenglandandwales/census2021',
    usedFor: 'broad occupation and industry reference distributions',
  },
  {
    id: 'ons-age-households',
    organisation: 'Office for National Statistics',
    title: 'Population and household estimates, England and Wales: Census 2021',
    url: 'https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/bulletins/populationandhouseholdestimatesenglandandwales/census2021unroundeddata',
    usedFor: 'age structure and household reference totals',
  },
  {
    id: 'ohid-mortality',
    organisation: 'Office for Health Improvement and Disparities',
    title: 'Mortality profile: life expectancy estimates',
    url: 'https://www.gov.uk/government/statistics/mortality-profile-may-2026-update',
    usedFor: 'regional and local-authority life-expectancy reference envelopes; generated ward values remain illustrative',
  },
  {
    id: 'ons-productivity',
    organisation: 'Office for National Statistics',
    title: 'Regional and subregional productivity in the UK',
    url: 'https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/labourproductivity/articles/regionalandsubregionalproductivityintheuk/february2020',
    usedFor: 'subregional productivity framing and plausible broad envelopes; synthetic ward GVA is not an official statistic',
  },
  {
    id: 'dft-tag-m31',
    organisation: 'Department for Transport',
    title: 'TAG unit M3.1: Highway assignment modelling',
    url: 'https://www.gov.uk/government/publications/tag-unit-m3-1-highway-assignment-modelling',
    usedFor: 'strategic assignment, capacity-restraint caveats and oversaturation interpretation',
  },
  {
    id: 'natural-england-alc',
    organisation: 'Natural England',
    title: 'Guide to assessing development proposals on agricultural land',
    url: 'https://www.gov.uk/government/publications/agricultural-land-assess-proposals-for-development/guide-to-assessing-development-proposals-on-agricultural-land',
    usedFor: 'Agricultural Land Classification categories; generated grades remain qualitative scenarios',
  },
];

export const TOWN_MODEL_ASSUMPTIONS = [
  'This is a synthetic scenario model: it generates internally coherent fictional places, not predictions or reconstructions of real English towns.',
  'Regional profiles are broad priors. Local geology, migration history, institutions and planning decisions vary much more than a region label can express.',
  'Residual coherent noise perturbs a structurally generated landscape; it is not the primary terrain mechanism.',
  'The major river is constrained to a declining longitudinal profile and carves a valley; tributaries are schematic. No calibrated rainfall–runoff, drainage-network, sediment-transport or hydraulic model is solved.',
  'Road congestion uses a static peak-hour capacity-delay approximation. It is not a microsimulation, dynamic assignment or calibrated junction model.',
  'Synthetic wards are compact analytical zones. They are not electoral wards, ONS output areas, LSOAs or MSOAs.',
  'Demographic outputs are aggregate scenario compositions derived from regional Census priors and urban context; they do not generate people or infer individual traits.',
  '“GVA per resident” is a low-certainty productivity estimate. Ward GDP is not an official small-area statistic and is deliberately not claimed.',
  'Air pollution, noise, life expectancy and biodiversity values are screening-level proxies with hand-set ranges, not regulatory, epidemiological or ecological assessments.',
  'Housing form, industrial legacy, deprivation, qualifications and health are connected by imposed ecological scenario correlations. These dependencies are not individual-level or causal claims.',
  'All displayed estimate ranges are hand-set sensitivity reminders. They are not confidence intervals, prediction intervals or empirically calibrated uncertainty bounds.',
];
