import type { EnglishRegion, GeologyUnit, HousingType } from './types';

export interface RegionProfile {
  id: EnglishRegion;
  label: string;
  landscapeArchetypes: string[];
  baseElevationM: number;
  reliefM: number;
  rainfallFactor: number;
  woodlandShare: number;
  moorlandShare: number;
  industrialLegacy: number;
  portPropensity: number;
  universityPropensity: number;
  terraceBias: number;
  vernacularTerrace: Extract<HousingType, 'stone terrace' | 'red-brick terrace'>;
  pm25BackgroundUgM3: number;
  lifeExpectancyBaselineYears: number;
  level4QualificationShare: number;
  agePrior: Record<string, number>;
  ethnicityPrior: Record<string, number>;
  employmentPrior: Record<string, number>;
  geology: GeologyUnit[];
}

const unit = (
  id: string,
  name: string,
  period: string,
  family: GeologyUnit['family'],
  share: number,
  hardness: number,
  permeability: number,
  fertility: number,
  resource: GeologyUnit['resource'],
  mapColour: string,
): GeologyUnit => ({
  id,
  name,
  period,
  family,
  share,
  hardness,
  permeability,
  fertility,
  resource,
  mapColour,
});

const standardAge = (olderAdjustment = 0, studentAdjustment = 0): Record<string, number> => ({
  '0-15': 0.18 - olderAdjustment * 0.25,
  '16-24': 0.105 + studentAdjustment,
  '25-44': 0.26 - olderAdjustment * 0.25 - studentAdjustment * 0.25,
  '45-64': 0.265,
  '65+': 0.19 + olderAdjustment - studentAdjustment * 0.75,
});

export const REGION_PROFILES: Record<EnglishRegion, RegionProfile> = {
  'north-east': {
    id: 'north-east',
    label: 'North East',
    landscapeArchetypes: ['Tyne–Wear lowlands and coalfield edge', 'Durham limestone plateau', 'Northumbrian upland fringe'],
    baseElevationM: 68,
    reliefM: 245,
    rainfallFactor: 1.06,
    woodlandShare: 0.12,
    moorlandShare: 0.12,
    industrialLegacy: 0.85,
    portPropensity: 0.7,
    universityPropensity: 0.55,
    terraceBias: 0.88,
    vernacularTerrace: 'red-brick terrace',
    pm25BackgroundUgM3: 7.2,
    lifeExpectancyBaselineYears: 79.1,
    level4QualificationShare: 0.286,
    agePrior: standardAge(0.01, -0.005),
    ethnicityPrior: { White: 0.935, Asian: 0.037, Black: 0.01, Mixed: 0.013, Other: 0.005 },
    employmentPrior: { manufacturing: 0.13, logistics: 0.08, public: 0.29, knowledge: 0.17, retailHospitality: 0.23, primary: 0.1 },
    geology: [
      unit('ne-coal', 'Pennine Coal Measures', 'Carboniferous', 'coal-measures', 0.34, 0.48, 0.28, 0.55, 'coal', '#71675d'),
      unit('ne-sand', 'Carboniferous sandstone and mudstone', 'Carboniferous', 'sandstone', 0.3, 0.67, 0.48, 0.46, 'stone', '#9b8060'),
      unit('ne-lime', 'Magnesian Limestone', 'Permian', 'limestone', 0.22, 0.76, 0.76, 0.62, 'stone', '#d6c789'),
      unit('ne-mud', 'Mudstone-dominated sedimentary bedrock', 'Carboniferous–Permian', 'mudstone-clay', 0.14, 0.35, 0.18, 0.7, 'clay', '#967f73'),
    ],
  },
  'north-west': {
    id: 'north-west',
    label: 'North West',
    landscapeArchetypes: ['Lancashire coalfield and coastal plain', 'Cumbrian glaciated fringe', 'Cheshire sandstone plain'],
    baseElevationM: 82,
    reliefM: 330,
    rainfallFactor: 1.28,
    woodlandShare: 0.14,
    moorlandShare: 0.15,
    industrialLegacy: 0.9,
    portPropensity: 0.75,
    universityPropensity: 0.62,
    terraceBias: 0.92,
    vernacularTerrace: 'red-brick terrace',
    pm25BackgroundUgM3: 7.8,
    lifeExpectancyBaselineYears: 79.4,
    level4QualificationShare: 0.312,
    agePrior: standardAge(0.012, 0),
    ethnicityPrior: { White: 0.87, Asian: 0.075, Black: 0.024, Mixed: 0.022, Other: 0.009 },
    employmentPrior: { manufacturing: 0.12, logistics: 0.1, public: 0.26, knowledge: 0.2, retailHospitality: 0.24, primary: 0.08 },
    geology: [
      unit('nw-coal', 'Lancashire and Cheshire Coal Measures', 'Carboniferous', 'coal-measures', 0.28, 0.48, 0.25, 0.56, 'coal', '#70665c'),
      unit('nw-sand', 'Sherwood Sandstone', 'Triassic', 'sandstone', 0.25, 0.58, 0.82, 0.52, 'aggregate', '#bd8069'),
      unit('nw-lime', 'Carboniferous Limestone', 'Carboniferous', 'limestone', 0.22, 0.82, 0.78, 0.48, 'stone', '#c8c28e'),
      unit('nw-volc', 'Borrowdale volcanic and older rocks', 'Ordovician', 'volcanic', 0.25, 0.94, 0.22, 0.25, 'stone', '#807f78'),
    ],
  },
  'yorkshire-humber': {
    id: 'yorkshire-humber',
    label: 'Yorkshire and the Humber',
    landscapeArchetypes: ['Pennine coalfield and gritstone fringe', 'Vale and limestone escarpment', 'Humberhead levels'],
    baseElevationM: 72,
    reliefM: 285,
    rainfallFactor: 1.08,
    woodlandShare: 0.11,
    moorlandShare: 0.13,
    industrialLegacy: 0.82,
    portPropensity: 0.72,
    universityPropensity: 0.58,
    terraceBias: 0.86,
    vernacularTerrace: 'stone terrace',
    pm25BackgroundUgM3: 7.7,
    lifeExpectancyBaselineYears: 79.7,
    level4QualificationShare: 0.302,
    agePrior: standardAge(0.008, 0),
    ethnicityPrior: { White: 0.854, Asian: 0.097, Black: 0.021, Mixed: 0.02, Other: 0.008 },
    employmentPrior: { manufacturing: 0.13, logistics: 0.1, public: 0.26, knowledge: 0.18, retailHospitality: 0.23, primary: 0.1 },
    geology: [
      unit('yh-grit', 'Millstone Grit', 'Carboniferous', 'sandstone', 0.25, 0.82, 0.42, 0.35, 'stone', '#92785e'),
      unit('yh-coal', 'Yorkshire Coal Measures', 'Carboniferous', 'coal-measures', 0.27, 0.47, 0.24, 0.57, 'coal', '#6b6259'),
      unit('yh-lime', 'Permian and Jurassic limestone', 'Permian–Jurassic', 'limestone', 0.23, 0.77, 0.76, 0.64, 'stone', '#d2c48a'),
      unit('yh-clay', 'Jurassic mudstone and clay', 'Jurassic', 'mudstone-clay', 0.25, 0.3, 0.16, 0.76, 'clay', '#99877a'),
    ],
  },
  'east-midlands': {
    id: 'east-midlands',
    label: 'East Midlands',
    landscapeArchetypes: ['Trent valley and coalfield edge', 'Jurassic limestone ridge and clay vales', 'Lincolnshire fen margin'],
    baseElevationM: 63,
    reliefM: 185,
    rainfallFactor: 0.9,
    woodlandShare: 0.12,
    moorlandShare: 0.035,
    industrialLegacy: 0.68,
    portPropensity: 0.25,
    universityPropensity: 0.54,
    terraceBias: 0.72,
    vernacularTerrace: 'red-brick terrace',
    pm25BackgroundUgM3: 8.2,
    lifeExpectancyBaselineYears: 80.4,
    level4QualificationShare: 0.294,
    agePrior: standardAge(0.005, -0.002),
    ethnicityPrior: { White: 0.85, Asian: 0.086, Black: 0.035, Mixed: 0.022, Other: 0.007 },
    employmentPrior: { manufacturing: 0.15, logistics: 0.12, public: 0.23, knowledge: 0.18, retailHospitality: 0.22, primary: 0.1 },
    geology: [
      unit('em-coal', 'Nottinghamshire–Derbyshire Coal Measures', 'Carboniferous', 'coal-measures', 0.22, 0.47, 0.24, 0.57, 'coal', '#71675e'),
      unit('em-sand', 'Sherwood Sandstone', 'Triassic', 'sandstone', 0.24, 0.58, 0.84, 0.52, 'aggregate', '#bc7e67'),
      unit('em-lime', 'Jurassic limestone', 'Jurassic', 'limestone', 0.25, 0.76, 0.72, 0.68, 'stone', '#d7ca92'),
      unit('em-clay', 'Jurassic mudstone and clay', 'Jurassic', 'mudstone-clay', 0.29, 0.28, 0.14, 0.78, 'clay', '#9a887b'),
    ],
  },
  'west-midlands': {
    id: 'west-midlands',
    label: 'West Midlands',
    landscapeArchetypes: ['Midlands plateau and coalfield', 'Severn–Avon vale', 'Welsh border upland fringe'],
    baseElevationM: 78,
    reliefM: 215,
    rainfallFactor: 1.02,
    woodlandShare: 0.14,
    moorlandShare: 0.045,
    industrialLegacy: 0.82,
    portPropensity: 0.14,
    universityPropensity: 0.56,
    terraceBias: 0.75,
    vernacularTerrace: 'red-brick terrace',
    pm25BackgroundUgM3: 8.8,
    lifeExpectancyBaselineYears: 80.0,
    level4QualificationShare: 0.289,
    agePrior: standardAge(0.002, 0),
    ethnicityPrior: { White: 0.74, Asian: 0.135, Black: 0.064, Mixed: 0.032, Other: 0.029 },
    employmentPrior: { manufacturing: 0.16, logistics: 0.11, public: 0.24, knowledge: 0.18, retailHospitality: 0.23, primary: 0.08 },
    geology: [
      unit('wm-coal', 'South Staffordshire Coal Measures', 'Carboniferous', 'coal-measures', 0.27, 0.46, 0.23, 0.54, 'coal', '#70655c'),
      unit('wm-sand', 'Sherwood Sandstone', 'Triassic', 'sandstone', 0.26, 0.57, 0.83, 0.54, 'aggregate', '#bd8068'),
      unit('wm-mud', 'Mercia Mudstone', 'Triassic', 'mudstone-clay', 0.29, 0.3, 0.13, 0.72, 'clay', '#a0756d'),
      unit('wm-sil', 'Silurian limestone and shale', 'Silurian', 'limestone', 0.18, 0.75, 0.62, 0.5, 'stone', '#b8b28e'),
    ],
  },
  'east-of-england': {
    id: 'east-of-england',
    label: 'East of England',
    landscapeArchetypes: ['East Anglian till plateau', 'Chalk escarpment and dry valleys', 'Fen and coastal plain'],
    baseElevationM: 42,
    reliefM: 115,
    rainfallFactor: 0.79,
    woodlandShare: 0.11,
    moorlandShare: 0.015,
    industrialLegacy: 0.36,
    portPropensity: 0.58,
    universityPropensity: 0.5,
    terraceBias: 0.45,
    vernacularTerrace: 'red-brick terrace',
    pm25BackgroundUgM3: 8.3,
    lifeExpectancyBaselineYears: 81.1,
    level4QualificationShare: 0.323,
    agePrior: standardAge(0.025, -0.005),
    ethnicityPrior: { White: 0.865, Asian: 0.068, Black: 0.034, Mixed: 0.025, Other: 0.008 },
    employmentPrior: { manufacturing: 0.1, logistics: 0.12, public: 0.22, knowledge: 0.23, retailHospitality: 0.23, primary: 0.1 },
    geology: [
      unit('ee-chalk', 'Chalk Group', 'Cretaceous', 'chalk', 0.3, 0.66, 0.9, 0.66, 'stone', '#ded9af'),
      unit('ee-clay', 'London Clay and related clays', 'Palaeogene', 'mudstone-clay', 0.23, 0.25, 0.12, 0.68, 'clay', '#997f79'),
      unit('ee-mud', 'Gault and Lower Cretaceous mudstone', 'Cretaceous', 'mudstone-clay', 0.28, 0.34, 0.2, 0.8, 'clay', '#a08e7e'),
      unit('ee-sand', 'Crag Group sands', 'Neogene', 'sandstone', 0.19, 0.38, 0.88, 0.56, 'aggregate', '#caa77b'),
    ],
  },
  'london-fringe': {
    id: 'london-fringe',
    label: 'London fringe',
    landscapeArchetypes: ['Thames basin and gravel terraces', 'Metropolitan claylands', 'Chiltern or North Downs fringe'],
    baseElevationM: 48,
    reliefM: 135,
    rainfallFactor: 0.86,
    woodlandShare: 0.14,
    moorlandShare: 0.005,
    industrialLegacy: 0.5,
    portPropensity: 0.32,
    universityPropensity: 0.7,
    terraceBias: 0.4,
    vernacularTerrace: 'red-brick terrace',
    pm25BackgroundUgM3: 10.1,
    lifeExpectancyBaselineYears: 81.6,
    level4QualificationShare: 0.43,
    agePrior: standardAge(-0.005, 0.025),
    ethnicityPrior: { White: 0.59, Asian: 0.19, Black: 0.1, Mixed: 0.055, Other: 0.065 },
    employmentPrior: { manufacturing: 0.06, logistics: 0.1, public: 0.2, knowledge: 0.36, retailHospitality: 0.24, primary: 0.04 },
    geology: [
      unit('lf-clay', 'London Clay', 'Palaeogene', 'mudstone-clay', 0.36, 0.25, 0.1, 0.64, 'clay', '#927b78'),
      unit('lf-chalk', 'Chalk Group', 'Cretaceous', 'chalk', 0.25, 0.68, 0.91, 0.66, 'stone', '#ded9af'),
      unit('lf-lambeth', 'Lambeth Group sands and clays', 'Palaeogene', 'mudstone-clay', 0.23, 0.38, 0.45, 0.62, 'clay', '#c6aa78'),
      unit('lf-sand', 'Bagshot sands', 'Palaeogene', 'sandstone', 0.16, 0.4, 0.82, 0.46, 'aggregate', '#c29c73'),
    ],
  },
  'south-east': {
    id: 'south-east',
    label: 'South East',
    landscapeArchetypes: ['Wealden ridges and clay vales', 'Chalk downs and dip slope', 'Thames or coastal plain'],
    baseElevationM: 58,
    reliefM: 175,
    rainfallFactor: 0.89,
    woodlandShare: 0.19,
    moorlandShare: 0.012,
    industrialLegacy: 0.32,
    portPropensity: 0.67,
    universityPropensity: 0.62,
    terraceBias: 0.38,
    vernacularTerrace: 'red-brick terrace',
    pm25BackgroundUgM3: 8.7,
    lifeExpectancyBaselineYears: 81.7,
    level4QualificationShare: 0.381,
    agePrior: standardAge(0.02, 0),
    ethnicityPrior: { White: 0.863, Asian: 0.07, Black: 0.024, Mixed: 0.03, Other: 0.013 },
    employmentPrior: { manufacturing: 0.08, logistics: 0.09, public: 0.22, knowledge: 0.31, retailHospitality: 0.24, primary: 0.06 },
    geology: [
      unit('se-chalk', 'Chalk Group', 'Cretaceous', 'chalk', 0.3, 0.7, 0.9, 0.64, 'stone', '#ded8aa'),
      unit('se-clay', 'Weald and London clays', 'Cretaceous–Palaeogene', 'mudstone-clay', 0.3, 0.28, 0.12, 0.7, 'clay', '#967c77'),
      unit('se-sand', 'Greensand and Wealden sandstone', 'Cretaceous', 'sandstone', 0.24, 0.58, 0.74, 0.5, 'stone', '#b69b68'),
      unit('se-lime', 'Jurassic limestone fringe', 'Jurassic', 'limestone', 0.16, 0.74, 0.7, 0.63, 'stone', '#d2c48e'),
    ],
  },
  'south-west': {
    id: 'south-west',
    label: 'South West',
    landscapeArchetypes: ['Devon–Cornwall slate and granite uplands', 'Severn lowlands and limestone edge', 'Dorset–Somerset ridges and vales'],
    baseElevationM: 84,
    reliefM: 275,
    rainfallFactor: 1.18,
    woodlandShare: 0.18,
    moorlandShare: 0.1,
    industrialLegacy: 0.42,
    portPropensity: 0.82,
    universityPropensity: 0.48,
    terraceBias: 0.48,
    vernacularTerrace: 'stone terrace',
    pm25BackgroundUgM3: 6.8,
    lifeExpectancyBaselineYears: 81.3,
    level4QualificationShare: 0.345,
    agePrior: standardAge(0.045, -0.008),
    ethnicityPrior: { White: 0.93, Asian: 0.028, Black: 0.012, Mixed: 0.023, Other: 0.007 },
    employmentPrior: { manufacturing: 0.09, logistics: 0.07, public: 0.25, knowledge: 0.21, retailHospitality: 0.27, primary: 0.11 },
    geology: [
      unit('sw-granite', 'Cornubian granite', 'Permian', 'granite', 0.2, 0.96, 0.2, 0.22, 'metal', '#bd9d9c'),
      unit('sw-slate', 'Devonian slate and sandstone', 'Devonian', 'slate', 0.31, 0.76, 0.26, 0.4, 'stone', '#6e7880'),
      unit('sw-lime', 'Carboniferous and Jurassic limestone', 'Carboniferous–Jurassic', 'limestone', 0.23, 0.78, 0.78, 0.66, 'stone', '#cec38d'),
      unit('sw-red', 'Permo-Triassic red sandstone', 'Permian–Triassic', 'sandstone', 0.26, 0.54, 0.78, 0.61, 'aggregate', '#bd7966'),
    ],
  },
};

export const ENGLISH_REGION_OPTIONS = Object.values(REGION_PROFILES).map((profile) => ({
  value: profile.id,
  label: profile.label,
}));
