export {
  compositionalInformationPreservingGeneralistModel,
  createInitialCompositionalInformationPreservingGeneralistState,
  deriveCompositionalInformationPreservingGeneralistPolicies,
  playCompositionalInformationPreservingGeneralistRound,
} from "./compositionalGame";
export type {
  CompositionalInformationPreservingGeneralistConfig,
  CompositionalInformationPreservingGeneralistConfigInput,
  CompositionalInformationPreservingGeneralistHistoryPoint,
  CompositionalInformationPreservingGeneralistMetrics,
  CompositionalInformationPreservingGeneralistPolicies,
  CompositionalInformationPreservingGeneralistRoundEvent,
  CompositionalInformationPreservingGeneralistState,
} from "./types";
